kind: Pod
apiVersion: v1
metadata:
   name: nginx
   namespace: expense
spec: 
# one pod can contain multuple containers
  containers:  
  - name: nginx
    image: nginx 


    #arn:aws:iam::221082205666:policy/ExpenseMYSQLSecretRead