kind: Pod
apiVersion: v1
metadata:
  name: labels
  annotations:
     buildURL: "https://jenkins.com/expense/job/backend/23"
     imageregistry: "http://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx 