kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    resource:
    # soft limit
     request:
      memory: "68Mi"
      cpu: "100m"
      # hard limit
     limits:
      memory: "128Mi"
      cpu: "150m"