# kind: Pod
# apiVersion: v1
# metadata:
#   name: pod-secret
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     envFrom:
#     - secretRef:
#         name: myconfig




apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: dotfile-secret   # exact secret name
