apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these labels are replicaset labels
  labels:
    app: frontend
    tier: web
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
  #replicaset use these labels to find the pods for creating desired  number of replicas
    matchLabels:
       app: frontend
       tier: frontend
  # pod template    
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
