apiVersion: v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
 selector: 
  matchLabels:
   name: fluentd-elasticsearch
 template: 
   metadata: 
     labels:
      name: fluentd-elasticsearch
     spec:
       tolerations: 
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods    
      - key: node-role.kubernetes.io/control-plane
         operator: Exists
         effect: NoSchedule
       containers: 
       - name: fluentd-elasticsearch
         image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
         resource:
          limits:
            memory: 200Mi
          request:
            cpu: 100m 
            memory: 200Mi 
          volumeMounts: 
          - name: varlog 
            mountPath: /var/log
            readonly: true 
     # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important 
       volumes:
       - name: varlog
         hostPath:
          path: /var/log   
